# Generated by Django 3.0.2 on 2020-01-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_empleado', models.IntegerField(verbose_name='Carnet')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('no_flota', models.CharField(blank=True, max_length=11, verbose_name='Numero Flota')),
                ('no_movil', models.CharField(blank=True, max_length=11, verbose_name='Numero Celular')),
                ('vehiculo', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Vehiculo')),
                ('ficha_vehiculo', models.IntegerField(blank=True, verbose_name='Ficha del Vehiculo')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electronico')),
                ('area', models.CharField(choices=[('ADM', 'Administrativa'), ('NORTE', 'Zona Norte'), ('SUR', 'Zona Sur'), ('ESTE', 'Zona Este'), ('N/A', 'No asignado')], default='N/A', max_length=50, verbose_name='Area de trabajo')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
