# Generated by Django 3.0.2 on 2020-01-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpm_brigada_reten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='no_flota',
            field=models.CharField(blank=True, max_length=13, verbose_name='Numero Flota'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='no_movil',
            field=models.CharField(blank=True, max_length=13, verbose_name='Numero Celular'),
        ),
    ]
