# Generated by Django 3.0.2 on 2020-01-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpm_brigada_reten', '0002_auto_20200130_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.CharField(choices=[('ADM', 'Administrativa'), ('NORTE', 'Zona Norte'), ('SUR', 'Zona Sur'), ('ESTE', 'Zona Este'), ('LAB', 'Laboratorio'), ('AUTO', 'Automatizacion'), ('N/A', 'No asignado')], default='N/A', max_length=50, verbose_name='Area de trabajo'),
        ),
    ]
