# Generated by Django 3.0.2 on 2020-01-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpm_brigada_reten', '0003_auto_20200130_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ficha_vehiculo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ficha del Vehiculo'),
        ),
    ]
