# Generated by Django 3.0.2 on 2020-01-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpm_brigada_reten', '0004_auto_20200130_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='no_flota',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Numero Flota'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='no_movil',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Numero Celular'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Vehiculo'),
        ),
    ]
